version: '3.8'

services:
  medizin-app:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_NO_TELEMETRY=1
    stdin_open: true
    tty: true
    command: npm run dev

  # Optional: Production build service
  medizin-web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run build:web
    profiles:
      - production