/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProcedureContentRenderer`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProcedureLayout`; params?: Router.UnknownInputParams; } | { pathname: `/components/ScrollContainer`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/styles/theme`; params?: Router.UnknownInputParams; } | { pathname: `/styles/commonStyles`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Card`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProcedureContentRenderer`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProcedureLayout`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ScrollContainer`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/components`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/commonStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/components/BackButton${`?${string}` | `#${string}` | ''}` | `/components/Card${`?${string}` | `#${string}` | ''}` | `/components/ProcedureContentRenderer${`?${string}` | `#${string}` | ''}` | `/components/ProcedureLayout${`?${string}` | `#${string}` | ''}` | `/components/ScrollContainer${`?${string}` | `#${string}` | ''}` | `/components/ThemeContext${`?${string}` | `#${string}` | ''}` | `/components${`?${string}` | `#${string}` | ''}` | `/styles/theme${`?${string}` | `#${string}` | ''}` | `/styles/commonStyles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProcedureContentRenderer`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProcedureLayout`; params?: Router.UnknownInputParams; } | { pathname: `/components/ScrollContainer`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/styles/theme`; params?: Router.UnknownInputParams; } | { pathname: `/styles/commonStyles`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
